# Generated by Django 4.2.28 on 2026-03-03 10:18

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        ("extras", "0132_approval_workflow_seed_data"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("intent_networking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("intent_id", models.CharField(db_index=True, max_length=200, unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("intent_type", models.CharField(db_index=True, max_length=50)),
                ("intent_data", models.JSONField()),
                ("change_ticket", models.CharField(blank=True, max_length=50)),
                ("approved_by", models.CharField(blank=True, max_length=200)),
                ("git_commit_sha", models.CharField(blank=True, max_length=40)),
                ("git_branch", models.CharField(blank=True, max_length=200)),
                ("git_pr_number", models.PositiveIntegerField(blank=True, null=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="intents", to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent",
                "verbose_name_plural": "Intents",
                "ordering": ["-created"],
                "permissions": [
                    ("approve_intent", "Can approve intents for deployment"),
                    ("deploy_intent", "Can trigger intent deployment"),
                    ("rollback_intent", "Can trigger intent rollback"),
                ],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ResolutionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("intent_version", models.PositiveIntegerField()),
                ("primitives", models.JSONField(default=list)),
                ("vrf_name", models.CharField(blank=True, max_length=100)),
                ("requires_new_vrf", models.BooleanField(default=False)),
                ("requires_mpls", models.BooleanField(default=False)),
                ("allocated_rds", models.JSONField(default=dict)),
                ("allocated_rts", models.JSONField(default=dict)),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_by", models.CharField(blank=True, max_length=200)),
                (
                    "affected_devices",
                    models.ManyToManyField(blank=True, related_name="intent_resolutions", to="dcim.device"),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_plans",
                        to="intent_networking.intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolution Plan",
                "verbose_name_plural": "Resolution Plans",
                "ordering": ["-resolved_at"],
                "unique_together": {("intent", "intent_version")},
            },
        ),
        migrations.CreateModel(
            name="RouteDistinguisher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("value", models.CharField(max_length=50, unique=True)),
                ("vrf_name", models.CharField(max_length=100)),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_distinguishers",
                        to="dcim.device",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocated_rds",
                        to="intent_networking.intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Distinguisher",
                "verbose_name_plural": "Route Distinguishers",
            },
        ),
        migrations.CreateModel(
            name="RouteDistinguisherPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("asn", models.PositiveIntegerField()),
                ("range_start", models.PositiveIntegerField()),
                ("range_end", models.PositiveIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Distinguisher Pool",
                "verbose_name_plural": "Route Distinguisher Pools",
            },
        ),
        migrations.CreateModel(
            name="RouteTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("value", models.CharField(max_length=50, unique=True)),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocated_rt",
                        to="intent_networking.intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Target",
                "verbose_name_plural": "Route Targets",
            },
        ),
        migrations.CreateModel(
            name="RouteTargetPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("asn", models.PositiveIntegerField()),
                ("range_start", models.PositiveIntegerField()),
                ("range_end", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Route Target Pool",
                "verbose_name_plural": "Route Target Pools",
            },
        ),
        migrations.CreateModel(
            name="VerificationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("passed", models.BooleanField()),
                ("triggered_by", models.CharField(default="deployment", max_length=50)),
                ("checks", models.JSONField(default=list)),
                ("measured_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("bgp_sessions_expected", models.PositiveIntegerField(default=0)),
                ("bgp_sessions_established", models.PositiveIntegerField(default=0)),
                ("prefixes_expected", models.PositiveIntegerField(default=0)),
                ("prefixes_received", models.PositiveIntegerField(default=0)),
                ("drift_details", models.JSONField(blank=True, default=dict)),
                ("remediation_triggered", models.BooleanField(default=False)),
                ("github_issue_url", models.URLField(blank=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="intent_networking.intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Result",
                "verbose_name_plural": "Verification Results",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.DeleteModel(
            name="IntentNetworkingExampleModel",
        ),
        migrations.AddField(
            model_name="routetarget",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="intent_networking.routetargetpool",
            ),
        ),
        migrations.AddField(
            model_name="routedistinguisher",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="intent_networking.routedistinguisherpool",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routedistinguisher",
            unique_together={("device", "vrf_name")},
        ),
    ]
