# Generated by Django 4.2.28 on 2026-03-09 10:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intent_networking", "0003_add_git_repository_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="deployment_strategy",
            field=models.CharField(default="all_at_once", max_length=20),
        ),
        migrations.AddField(
            model_name="intent",
            name="rendered_configs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="intent",
            name="scheduled_deploy_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="IntentAuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                ("actor", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("git_commit_sha", models.CharField(blank=True, max_length=40)),
                ("job_result_id", models.UUIDField(blank=True, null=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to="intent_networking.intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Entry",
                "verbose_name_plural": "Audit Entries",
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="IntentApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("decision", models.CharField(max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intent_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="intent_networking.intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Approval",
                "verbose_name_plural": "Intent Approvals",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("stage_order", models.PositiveIntegerField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rendered_configs", models.JSONField(blank=True, default=dict)),
                ("devices", models.ManyToManyField(blank=True, related_name="deployment_stages", to="dcim.device")),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_stages",
                        to="intent_networking.intent",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dcim.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment Stage",
                "verbose_name_plural": "Deployment Stages",
                "ordering": ["intent", "stage_order"],
                "unique_together": {("intent", "stage_order")},
            },
        ),
    ]
