# Generated by Django 4.2.28 on 2026-03-10 12:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("intent_networking", "0004_intent_deployment_strategy_intent_rendered_configs_and_more"),
    ]

    operations = [
        # ── Update intent_type choices to include all 14 domains ────
        migrations.AlterField(
            model_name="intent",
            name="intent_type",
            field=models.CharField(
                choices=[
                    # Legacy / Original
                    ("connectivity", "Connectivity"),
                    ("security", "Security"),
                    ("reachability", "Reachability"),
                    ("service", "Service"),
                    # 1. Layer 2 / Switching
                    ("vlan_provision", "VLAN Provisioning"),
                    ("l2_access_port", "Access Port"),
                    ("l2_trunk_port", "Trunk Port"),
                    ("lag", "Port Channel / LAG"),
                    ("mlag", "MLAG / MC-LAG"),
                    ("stp_policy", "Spanning Tree Policy"),
                    ("qinq", "QinQ / Double Tagging"),
                    ("pvlan", "Private VLAN"),
                    ("storm_control", "Storm Control"),
                    ("port_security", "Port Security / MAC Limit"),
                    ("dhcp_snooping", "DHCP Snooping"),
                    ("dai", "Dynamic ARP Inspection"),
                    ("ip_source_guard", "IP Source Guard"),
                    ("macsec", "MACsec"),
                    # 2. Layer 3 / Routing
                    ("static_route", "Static Route"),
                    ("ospf", "OSPF Adjacency / Area"),
                    ("bgp_ebgp", "BGP Peering (eBGP)"),
                    ("bgp_ibgp", "BGP Peering (iBGP)"),
                    ("isis", "IS-IS"),
                    ("eigrp", "EIGRP"),
                    ("route_redistribution", "Route Redistribution"),
                    ("route_policy", "Route Policy / Route Map"),
                    ("prefix_list", "Prefix List"),
                    ("vrf_basic", "VRF (non-MPLS)"),
                    ("bfd", "BFD"),
                    ("pbr", "Policy-Based Routing"),
                    ("ipv6_dual_stack", "IPv6 Dual-Stack Interface"),
                    ("ospfv3", "OSPFv3 (IPv6)"),
                    ("bgp_ipv6_af", "BGP IPv6 Address Family"),
                    ("fhrp", "HSRP / VRRP / GLBP"),
                    # 3. MPLS & Service Provider
                    ("mpls_l3vpn", "MPLS L3VPN"),
                    ("mpls_l2vpn", "MPLS L2VPN / VPLS"),
                    ("pseudowire", "Pseudowire / EoMPLS"),
                    ("evpn_mpls", "EVPN over MPLS"),
                    ("ldp", "LDP"),
                    ("rsvp_te", "RSVP-TE Tunnel"),
                    ("sr_mpls", "Segment Routing MPLS"),
                    ("srv6", "SRv6"),
                    ("6pe_6vpe", "6PE / 6VPE"),
                    ("mvpn", "Multicast VRF / mVPN"),
                    # 4. Data Centre / Overlay
                    ("evpn_vxlan_fabric", "VXLAN EVPN Fabric"),
                    ("l2vni", "L2VNI Provisioning"),
                    ("l3vni", "L3VNI / IP VRF over VXLAN"),
                    ("bgp_evpn_af", "BGP EVPN Address Family"),
                    ("anycast_gateway", "Anycast Gateway"),
                    ("vtep", "VTEP Configuration"),
                    ("evpn_multisite", "Multi-Site EVPN"),
                    ("dc_underlay", "DC Underlay (OSPF/BGP)"),
                    ("dc_mlag", "MLAG in DC Fabric"),
                    # 5. Security & Firewalling
                    ("acl", "ACL"),
                    ("zbf", "Zone-Based Firewall"),
                    ("ipsec_s2s", "IPSec Site-to-Site Tunnel"),
                    ("ipsec_ikev2", "IPSec with IKEv2"),
                    ("gre_tunnel", "GRE Tunnel"),
                    ("gre_over_ipsec", "GRE over IPSec"),
                    ("dmvpn", "DMVPN"),
                    ("macsec_policy", "MACsec Policy"),
                    ("copp", "CoPP (Control Plane Policing)"),
                    ("urpf", "uRPF"),
                    ("dot1x_nac", "802.1X / NAC"),
                    ("aaa", "RADIUS / TACACS AAA"),
                    ("ra_guard", "RA Guard (IPv6)"),
                    ("ssl_inspection", "SSL/TLS Inspection"),
                    # 6. WAN & SD-WAN
                    ("wan_uplink", "WAN Uplink / Dual ISP"),
                    ("bgp_isp", "BGP to ISP"),
                    ("sdwan_overlay", "SD-WAN Overlay"),
                    ("sdwan_app_policy", "SD-WAN Application Policy"),
                    ("sdwan_qos", "SD-WAN QoS Policy"),
                    ("sdwan_dia", "SD-WAN DIA"),
                    ("nat_pat", "NAT / PAT"),
                    ("nat64", "NAT64"),
                    ("wan_failover", "WAN Redundancy / Failover"),
                    # 7. Wireless
                    ("wireless_ssid", "SSID Provisioning"),
                    ("wireless_vlan_map", "VLAN to SSID Mapping"),
                    ("wireless_dot1x", "802.1X Wireless"),
                    ("wireless_guest", "Guest Wireless / Captive Portal"),
                    ("wireless_rf", "RF Policy"),
                    ("wireless_qos", "QoS for Wireless"),
                    ("wireless_band_steer", "Band Steering"),
                    ("wireless_roam", "Fast Roaming / 802.11r"),
                    ("wireless_segment", "Wireless Segmentation"),
                    ("wireless_mesh", "Mesh Wireless"),
                    ("wireless_flexconnect", "FlexConnect / Local Switching"),
                    # 8. Cloud & Hybrid Cloud
                    ("cloud_vpc_peer", "VPC / VNet Peering"),
                    ("cloud_transit_gw", "Transit Gateway / Hub-Spoke"),
                    ("cloud_direct_connect", "Cloud Direct Connect"),
                    ("cloud_vpn_gw", "Cloud VPN Gateway"),
                    ("cloud_bgp", "BGP to Cloud Provider"),
                    ("cloud_security_group", "Cloud Firewall / Security Group"),
                    ("cloud_nat", "Cloud NAT"),
                    ("cloud_route_table", "Cloud Route Table"),
                    ("hybrid_dns", "Hybrid DNS"),
                    ("cloud_sdwan", "Cloud SD-WAN Integration"),
                    # 9. QoS
                    ("qos_classify", "Traffic Classification"),
                    ("qos_dscp_mark", "DSCP Marking"),
                    ("qos_cos_remark", "CoS Remarking"),
                    ("qos_queue", "Queuing Policy"),
                    ("qos_police", "Policing"),
                    ("qos_shape", "Traffic Shaping"),
                    ("qos_trust", "QoS Trust Boundary"),
                    # 10. Multicast
                    ("multicast_pim_sm", "PIM Sparse Mode"),
                    ("multicast_pim_ssm", "PIM SSM"),
                    ("igmp_snooping", "IGMP Snooping"),
                    ("multicast_vrf", "Multicast VRF"),
                    ("msdp", "MSDP"),
                    # 11. Management & Operations
                    ("mgmt_ntp", "NTP"),
                    ("mgmt_dns_dhcp", "DNS / DHCP"),
                    ("mgmt_snmp", "SNMP"),
                    ("mgmt_syslog", "Syslog"),
                    ("mgmt_netflow", "NetFlow / IPFIX"),
                    ("mgmt_telemetry", "gRPC / Streaming Telemetry"),
                    ("mgmt_ssh", "SSH Access Control"),
                    ("mgmt_aaa_device", "TACACS / RADIUS for Device Mgmt"),
                    ("mgmt_interface", "Loopback / Management Interface"),
                    ("mgmt_lldp_cdp", "LLDP / CDP Policy"),
                    ("mgmt_stp_root", "Spanning Tree Root"),
                    # 12. Reachability (expanded)
                    ("reachability_static", "Static Reachability"),
                    ("reachability_bgp_network", "BGP Network Statement"),
                    ("reachability_floating", "Floating Static / Backup Route"),
                    ("reachability_ip_sla", "IP SLA Probe"),
                    # 13. Service (expanded)
                    ("service_lb_vip", "Load Balancer VIP"),
                    ("service_dns", "DNS Record"),
                    ("service_dhcp", "DHCP Pool / Scope"),
                    ("service_nat", "NAT Entry (Service)"),
                    ("service_proxy", "Proxy / Service Insertion"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        # ── VXLAN VNI Pool & Allocation ─────────────────────────────
        migrations.CreateModel(
            name="VxlanVniPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "range_start",
                    models.PositiveIntegerField(help_text="First VNI value in pool e.g. 10000"),
                ),
                (
                    "range_end",
                    models.PositiveIntegerField(help_text="Last VNI value in pool e.g. 19999"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant-specific pool. Leave blank for shared pool.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "VXLAN VNI Pool",
                "verbose_name_plural": "VXLAN VNI Pools",
            },
        ),
        migrations.CreateModel(
            name="VniAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(help_text="VNI value e.g. 10042", unique=True),
                ),
                (
                    "vni_type",
                    models.CharField(
                        choices=[("l2", "Layer 2 VNI"), ("l3", "Layer 3 VNI")],
                        help_text="Whether this VNI is for L2VNI or L3VNI.",
                        max_length=10,
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocated_vnis",
                        to="intent_networking.intent",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="intent_networking.vxlanvnipool",
                    ),
                ),
            ],
            options={
                "verbose_name": "VNI Allocation",
                "verbose_name_plural": "VNI Allocations",
            },
        ),
        # ── Tunnel ID Pool & Allocation ─────────────────────────────
        migrations.CreateModel(
            name="TunnelIdPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "range_start",
                    models.PositiveIntegerField(help_text="First tunnel ID e.g. 100"),
                ),
                (
                    "range_end",
                    models.PositiveIntegerField(help_text="Last tunnel ID e.g. 999"),
                ),
            ],
            options={
                "verbose_name": "Tunnel ID Pool",
                "verbose_name_plural": "Tunnel ID Pools",
            },
        ),
        migrations.CreateModel(
            name="TunnelIdAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(help_text="Tunnel interface number e.g. 100"),
                ),
                (
                    "tunnel_type",
                    models.CharField(
                        choices=[("ipsec", "IPSec"), ("gre", "GRE"), ("dmvpn", "DMVPN")],
                        max_length=20,
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tunnel_id_allocations",
                        to="dcim.device",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocated_tunnel_ids",
                        to="intent_networking.intent",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="intent_networking.tunnelidpool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tunnel ID Allocation",
                "verbose_name_plural": "Tunnel ID Allocations",
                "unique_together": {("device", "value")},
            },
        ),
        # ── Managed Loopback Pool & Allocation ──────────────────────
        migrations.CreateModel(
            name="ManagedLoopbackPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "prefix",
                    models.CharField(
                        help_text="CIDR prefix to allocate /32s from e.g. 192.0.2.0/24",
                        max_length=50,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant-specific pool. Leave blank for shared pool.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Loopback Pool",
                "verbose_name_plural": "Managed Loopback Pools",
            },
        ),
        migrations.CreateModel(
            name="ManagedLoopback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Allocated /32 IP e.g. 192.0.2.1",
                        unique=True,
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_loopbacks",
                        to="dcim.device",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocated_loopbacks",
                        to="intent_networking.intent",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="intent_networking.managedloopbackpool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Loopback",
                "verbose_name_plural": "Managed Loopbacks",
                "unique_together": {("device", "pool")},
            },
        ),
        # ── Wireless VLAN Pool & Allocation ─────────────────────────
        migrations.CreateModel(
            name="WirelessVlanPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "range_start",
                    models.PositiveIntegerField(help_text="First VLAN ID e.g. 200"),
                ),
                (
                    "range_end",
                    models.PositiveIntegerField(help_text="Last VLAN ID e.g. 299"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site this pool belongs to. Leave blank for global pool.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wireless_vlan_pools",
                        to="dcim.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wireless VLAN Pool",
                "verbose_name_plural": "Wireless VLAN Pools",
            },
        ),
        migrations.CreateModel(
            name="WirelessVlanAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "vlan_id",
                    models.PositiveIntegerField(help_text="Allocated VLAN ID e.g. 201"),
                ),
                (
                    "ssid_name",
                    models.CharField(
                        help_text="SSID this VLAN is mapped to",
                        max_length=100,
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocated_wireless_vlans",
                        to="intent_networking.intent",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="intent_networking.wirelessvlanpool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wireless VLAN Allocation",
                "verbose_name_plural": "Wireless VLAN Allocations",
                "unique_together": {("pool", "vlan_id")},
            },
        ),
    ]
