# Generated by Django 4.2.28

from django.db import migrations


class Migration(migrations.Migration):
    """Remove the custom RD/RT pool models.

    Route-distinguisher and route-target allocation is now handled by
    Nautobot's native ipam.VRF, ipam.RouteTarget, and ipam.Namespace models.
    """

    dependencies = [
        ("intent_networking", "0005_vxlanvnipool_vniallocation_tunnelidpool_and_more"),
    ]

    operations = [
        # Drop child tables first (they have FK constraints to pools & intent)
        migrations.DeleteModel(name="RouteDistinguisher"),
        migrations.DeleteModel(name="RouteTarget"),
        # Now drop the pool tables
        migrations.DeleteModel(name="RouteDistinguisherPool"),
        migrations.DeleteModel(name="RouteTargetPool"),
    ]
