# Generated by Django 4.2.28 on 2026-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_networking', '0011_intent_backup_verification_to_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='verification_schedule',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verificationresult',
            name='escalation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='verificationresult',
            name='pyats_diff_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
